version: "2"
services:
  timetable_service:
    container_name: timetable_service
    build: ./
    restart: always
    ports:
      - "3002:3000"
    depends_on:
      - timetable_service_db
    command: npm run dev
    networks:
      - budget_app_network
  timetable_service_db:
    container_name: timetable_service_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: timetable_service_password
      MYSQL_DATABASE: timetable_service
    ports:
      - "3308:3306"
    networks:
      - budget_app_network
networks:
  budget_app_network:
    external: true