version: "2"
services:
  timetable_service:
    container_name: timetable_service
    build: ./
    restart: always
    ports:
      - "3003:3000"
    command: npm run dev
    networks:
      - budget_app_network
networks:
  budget_app_network:
    external: true