version: "2"
services:
  timetable_service:
    container_name: timetable_service
    build: ./
    restart: always
    ports:
      - "3002:3000"
    networks:
      - budget_app_network
  # timetable_service_db:
  #   container_name: timetable_service_db
  #   build: mongo:4
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - budget_app_network
networks:
  budget_app_network:
    external: true